# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: TerraformCLI@0
    displayName: Intialize
    inputs:
      command: 'init'
      backendType: 'azurerm'
      backendServiceArm: 'Azure subscription 1(e83f45e6-ab20-4d00-9b9a-5bf804ca39bd)'
      backendAzureRmResourceGroupName: 'Zain-Terraform'
      backendAzureRmStorageAccountName: 'zainterraformuks'
      backendAzureRmContainerName: 'zainterratrain'
      backendAzureRmKey: 'terraform.tfstate'
      backendAzureRmResourceGroupLocation: 'uksouth'
      ensureBackend: true

  - task: TerraformCLI@0
    displayName: Validation
    inputs:
      command: 'validate'
      allowTelemetryCollection: true


  - task: TerraformCLI@0
    displayName: Planning
    inputs:
      command: 'plan'
      runAzLogin: true
      allowTelemetryCollection: true
      environmentServiceName: 'Aseem-Azure Sub'

  - task: TerraformCLI@0
    displayName: Application
    inputs:
      command: 'apply'
      runAzLogin: true
      allowTelemetryCollection: true
      environmentServiceName: 'Aseem-Azure Sub'