# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: TerraformCLI@0
    displayName: Intialize
    inputs:
      command: 'init'
      allowTelemetryCollection: true

  - task: TerraformCLI@0
    displayName: Validation
    inputs:
      command: 'validate'
      allowTelemetryCollection: true


  - task: TerraformCLI@0
    displayName: Planning
    inputs:
      command: 'plan'
      runAzLogin: true
      allowTelemetryCollection: true
      environmentServiceName: 'Aseem-Azure Sub'

  - task: TerraformCLI@0
    displayName: Application
    inputs:
      command: 'apply'
      runAzLogin: true
      allowTelemetryCollection: true
      environmentServiceName: 'Aseem-Azure Sub'